let lists=[{
	"createUserId": 34,
	"createTime": "2020-04-14 18:25:52",
	"updateUserId": 34,
	"updateTime": "2020-04-14 18:25:52",
	"beginTime": null,
	"endTime": null,
	"version": null,
	"permId": 31,
	"permPid": 0,
	"permName": "首页",
	"permRequest": "/index",
	"permSort": 1,
	"permType": 1,
	"permIcon": "1",
	"permStatus": 1,
	"children": [],
	"parentName": null,
	"level": 1,
	"permTypeName": "菜单",
	"permStatusName": "启用"
}, {
	"createUserId": 34,
	"createTime": "2020-04-14 18:26:51",
	"updateUserId": 34,
	"updateTime": "2020-04-14 18:26:51",
	"beginTime": null,
	"endTime": null,
	"version": null,
	"permId": 32,
	"permPid": 0,
	"permName": "作业管理",
	"permRequest": "/job",
	"permSort": 2,
	"permType": 1,
	"permIcon": "1",
	"permStatus": 1,
	"children": [{
		"createUserId": 34,
		"createTime": "2020-04-14 18:27:35",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:27:35",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 33,
		"permPid": 32,
		"permName": "基础管理",
		"permRequest": "/basics ",
		"permSort": 1,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "作业管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}, {
		"createUserId": 34,
		"createTime": "2020-04-14 18:31:50",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:31:50",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 37,
		"permPid": 32,
		"permName": "订单管理",
		"permRequest": "/order",
		"permSort": 2,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "作业管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}, {
		"createUserId": 34,
		"createTime": "2020-04-14 18:32:28",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:32:28",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 38,
		"permPid": 32,
		"permName": "运单管理",
		"permRequest": "/shipping",
		"permSort": 3,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "作业管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}, {
		"createUserId": 34,
		"createTime": "2020-04-14 18:33:02",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:33:02",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 39,
		"permPid": 32,
		"permName": "轨迹跟踪",
		"permRequest": "/trajectory",
		"permSort": 4,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "作业管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}, {
		"createUserId": 34,
		"createTime": "2020-04-14 18:33:46",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:33:46",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 40,
		"permPid": 32,
		"permName": "异常管理",
		"permRequest": "/exception",
		"permSort": 5,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "作业管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}],
	"parentName": null,
	"level": 1,
	"permTypeName": "菜单",
	"permStatusName": "启用"
}, {
	"createUserId": 34,
	"createTime": "2020-04-14 18:34:41",
	"updateUserId": 34,
	"updateTime": "2020-04-14 18:34:41",
	"beginTime": null,
	"endTime": null,
	"version": null,
	"permId": 41,
	"permPid": 0,
	"permName": "财务管理",
	"permRequest": "/finance",
	"permSort": 3,
	"permType": 1,
	"permIcon": "1",
	"permStatus": 1,
	"children": [{
		"createUserId": 34,
		"createTime": "2020-04-14 18:35:14",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:35:14",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 42,
		"permPid": 41,
		"permName": "账户管理",
		"permRequest": "/account",
		"permSort": 1,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "财务管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}, {
		"createUserId": 34,
		"createTime": "2020-04-14 18:35:49",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:35:49",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 43,
		"permPid": 41,
		"permName": "结算管理 ",
		"permRequest": "/settlement",
		"permSort": 2,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "财务管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}],
	"parentName": null,
	"level": 1,
	"permTypeName": "菜单",
	"permStatusName": "启用"
}, {
	"createUserId": 34,
	"createTime": "2020-04-14 18:36:16",
	"updateUserId": 34,
	"updateTime": "2020-04-14 18:36:16",
	"beginTime": null,
	"endTime": null,
	"version": null,
	"permId": 44,
	"permPid": 0,
	"permName": "用户管理",
	"permRequest": "/user",
	"permSort": 4,
	"permType": 1,
	"permIcon": "1",
	"permStatus": 1,
	"children": [{
		"createUserId": 34,
		"createTime": "2020-04-14 18:36:40",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:36:40",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 45,
		"permPid": 44,
		"permName": "用户信息",
		"permRequest": "/userMessage",
		"permSort": 1,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "用户管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}, {
		"createUserId": 34,
		"createTime": "2020-04-14 18:37:17",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:37:17",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 46,
		"permPid": 44,
		"permName": "货主管理",
		"permRequest": "/shipper",
		"permSort": 2,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "用户管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}, {
		"createUserId": 34,
		"createTime": "2020-04-14 18:37:51",
		"updateUserId": 34,
		"updateTime": "2020-04-14 18:37:51",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 47,
		"permPid": 44,
		"permName": "车主管理",
		"permRequest": "/driver",
		"permSort": 3,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [],
		"parentName": "用户管理",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}],
	"parentName": null,
	"level": 1,
	"permTypeName": "菜单",
	"permStatusName": "启用"
}, {
	"createUserId": 34,
	"createTime": "2020-04-15 09:26:02",
	"updateUserId": 34,
	"updateTime": "2020-04-15 09:26:02",
	"beginTime": null,
	"endTime": null,
	"version": null,
	"permId": 51,
	"permPid": 0,
	"permName": "1123",
	"permRequest": "123",
	"permSort": 12312,
	"permType": 1,
	"permIcon": "1",
	"permStatus": 1,
	"children": [{
		"createUserId": 34,
		"createTime": "2020-04-15 10:20:24",
		"updateUserId": 34,
		"updateTime": "2020-04-15 10:20:24",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 54,
		"permPid": 51,
		"permName": "1",
		"permRequest": "1",
		"permSort": 1,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [{
			"createUserId": 34,
			"createTime": "2020-04-15 13:52:08",
			"updateUserId": 34,
			"updateTime": "2020-04-15 13:52:08",
			"beginTime": null,
			"endTime": null,
			"version": null,
			"permId": 55,
			"permPid": 54,
			"permName": "2",
			"permRequest": "2",
			"permSort": 2,
			"permType": 1,
			"permIcon": "2",
			"permStatus": 1,
			"children": [{
				"createUserId": 34,
				"createTime": "2020-04-15 13:52:28",
				"updateUserId": 34,
				"updateTime": "2020-04-15 13:52:28",
				"beginTime": null,
				"endTime": null,
				"version": null,
				"permId": 56,
				"permPid": 55,
				"permName": "3",
				"permRequest": "3",
				"permSort": 3,
				"permType": 1,
				"permIcon": "3",
				"permStatus": 1,
				"children": [{
					"createUserId": 34,
					"createTime": "2020-04-15 13:52:44",
					"updateUserId": 34,
					"updateTime": "2020-04-15 13:52:44",
					"beginTime": null,
					"endTime": null,
					"version": null,
					"permId": 57,
					"permPid": 56,
					"permName": "4",
					"permRequest": "5",
					"permSort": 5,
					"permType": 1,
					"permIcon": "5",
					"permStatus": 1,
					"children": [],
					"parentName": "3",
					"level": 5,
					"permTypeName": "菜单",
					"permStatusName": "启用"
				}],
				"parentName": "2",
				"level": 4,
				"permTypeName": "菜单",
				"permStatusName": "启用"
			}],
			"parentName": "1",
			"level": 3,
			"permTypeName": "菜单",
			"permStatusName": "启用"
		}],
		"parentName": "1123",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}, {
		"createUserId": 34,
		"createTime": "2020-04-15 09:26:56",
		"updateUserId": 34,
		"updateTime": "2020-04-15 09:57:54",
		"beginTime": null,
		"endTime": null,
		"version": null,
		"permId": 52,
		"permPid": 51,
		"permName": "菜单ddd",
		"permRequest": "1111",
		"permSort": 11,
		"permType": 1,
		"permIcon": "1",
		"permStatus": 1,
		"children": [{
			"createUserId": 34,
			"createTime": "2020-04-15 09:27:22",
			"updateUserId": 34,
			"updateTime": "2020-04-15 09:27:22",
			"beginTime": null,
			"endTime": null,
			"version": null,
			"permId": 53,
			"permPid": 52,
			"permName": "按钮1",
			"permRequest": "1",
			"permSort": 1,
			"permType": 2,
			"permIcon": "1",
			"permStatus": 1,
			"children": [],
			"parentName": "菜单ddd",
			"level": 3,
			"permTypeName": "按钮",
			"permStatusName": "启用"
		}],
		"parentName": "1123",
		"level": 2,
		"permTypeName": "菜单",
		"permStatusName": "启用"
	}],
	"parentName": null,
	"level": 1,
	"permTypeName": "菜单",
	"permStatusName": "启用"
}];
export default{
    lists
}